version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: practice-server-db
    environment:
      POSTGRES_DB: practice-server-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-start:
    build:
      context: ./database
      dockerfile: Dockerfile
    depends_on:
      - postgres

  next-js-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-start

volumes:
  postgres_data:
